/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clinicaapp.Presentacion;

import com.mycompany.clinicaapp.LogicaDelNegocio.GestorCita;
import com.mycompany.clinicaapp.Modelos.Medico;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.clinicaapp.LogicaDelNegocio.GestorMedico;
import com.mycompany.clinicaapp.Modelos.Cita;
import com.mycompany.clinicaapp.Utilidades.BotonDiagnosticoCita;
import com.mycompany.clinicaapp.Utilidades.BotonTablaCita;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.TableColumn;
/**
 *
 * @author hecto
 */
public class PanelMedico extends javax.swing.JFrame {

    /**
     * Creates new form PanelMedico
     */
    public PanelMedico() {
        initComponents();
        cargarCitasMedico();

        
    }
    
    private void cargarCitasMedico() {
    GestorMedico gestorMedico = GestorMedico.getInstanciaMedico();
    GestorCita gestorCita = GestorCita.getInstanciaCita();

    Medico medicoActual = gestorMedico.getMedicoActual();

    if (medicoActual == null) {
        JOptionPane.showMessageDialog(this, "Error: No hay un médico logueado actualmente.");
        return;
    }

    List<Cita> citasMedico = gestorCita.consultarCitasMedico(medicoActual);

    DefaultTableModel modelo = new DefaultTableModel(
        new Object[]{"ID", "Fecha", "Paciente", "Motivo", "Acciones"}, 0
    ) {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return columna == 4; // solo la columna "Acciones" será editable
        }
    };

    for (Cita c : citasMedico) {
        modelo.addRow(new Object[]{
            c.getId(),
            c.getFecha(),
            c.getPaciente().getNombre(),
            c.getDiagnostico(), // aquí se muestra el motivo de la cita
            "Agregar diagnóstico" // botón
        });
}

Table1.setModel(modelo);
Table1.setRowHeight(32); //  usa el JTable que tienes en tu JFrame

TableColumn colAcciones = Table1.getColumn("Acciones");
colAcciones.setCellRenderer(new BotonDiagnosticoCita(gestorCita, Table1));
colAcciones.setCellEditor(new BotonDiagnosticoCita(gestorCita, Table1));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaPacientes = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPacientes.setViewportView(Table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(tablaPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablaPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JScrollPane tablaPacientes;
    // End of variables declaration//GEN-END:variables
}
